name: "Trigger Qa Automated"
author: "xcvdsfd"
description: "Trigger automated test actions through http requests"
inputs:
  token:
    description: "Github token. E.g. secrets.GITHUB_TOKEN"
    require: true
  bucket-prebuilt:
    description: "S3 Bucket used as release area of prebuilt binaries"
    default: "kungfu-prebuilt"
  qa_automated_repo:
    description: "qa-automated repo"
    default: "kfx-qa-automated"
  manual_artifact_name:
    description: "Manual trigger artifact_name"
    require: false
  manual_version:
    description: "Manual trigger artifact_version"
    require: false
  manual_repo:
    description: "Manual trigger repo_name"
    require: false
runs:
  using: "node20"
  main: "dist/index.js"