name: Trigger QA Automated
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo'
        required: true
        default: 'kungfu'
        type: string
      version:
        description: 'version'
        required: true
        default: '2.6.3-alpha.1'
        type: string
      artifact_name:
        description: 'artifact_name'
        required: true
        default: 'artifact-kungfu'
        type: string
      qa_automated_repo:
        description: 'qa_automated_repo'
        required: true
        default: 'kfx-qa-automated'
        type: string
      aws-user-region:
        default: "cn-northwest-1"
        type: string
        required: false

jobs:
  automated:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Crendentials (User)
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-user-region }}

      - name: trigger
        uses: kungfu-trader/action-qa-automated@v1.0-alpha
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
          manual_artifact_name: ${{ inputs.artifact_name }}
          manual_version: ${{ inputs.version }}
          manual_repo: ${{ inputs.repo }}
          qa_automated_repo: ${{ inputs.qa_automated_repo }}

